server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
      
  ratelimiter:
    instances:
      default:
        limit-for-period: 3
        limit-refresh-period: 10s
      
  retry:
    instances:
     foo-bar:
        max-attempts: 5  
        wait-duration: 1s
        enable-exponential-backoff: true  
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_service #?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  #proteção para serialização, com.fasterxml.jackson.databind.exc.InvalidDefinitionException:
  jackson:
  # para não serializar objetos nulos 
    default-property-inclusion: NON_NULL
    serialization: 
      fail-on-empty-beans: false
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    url: jdbc:postgresql://localhost:5432/book_service 
    user: root
    password: root
  sleuth:
    sampler:
      probability: 1.0 
#passando as config de docs para o gateway    
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs
