name: Continuous integration with Github

on: [push]
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Java JDK
      - uses: actions/setup-java@v3.4.1
      - with:
         Java-version: '11'
         distribution: 'adopt'
   

      


     
