name: Continuous integration with Github

on: [push]
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.1
        with:
          Java-version: '11'
          distribution: 'adopt'
      
      - name: Build Eureka Registry Server Container
        working-directory: ./service-registry
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build API-GATEWAY Server Container
        working-directory: ./gateway
        run: mvn spring-boot:build-image -DskipTests
     
      - name: Build API-CAMBIO Server Jar
        working-directory: ./cambio-service
        run: mvn clean package -DskipTests
  
      - name: Build API-BOOK Server Jar
        working-directory: ./book-service
        run: mvn clean package -DskipTests
     
      - name: Docker compose Build 
        working-directory: ./
        run: docker-compose build
        
      - name: Push to Docker Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/service-registry:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/service-registry:${{ github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/service-registry:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/service-registry:lates
          
          docker tag ${{ secrets.DOCKER_USERNAME }}/gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/gateway:${{ github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/gateway:latest
           
          docker tag ${{ secrets.DOCKER_USERNAME }}/cambio-service:latest ${{ secrets.DOCKER_USERNAME}}/cambio-service:${{ github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/cambio-service:latest ${{ secrets.DOCKER_USERNAME}}/cambio-service:latest
          
          docker tag ${{ secrets.DOCKER_USERNAME }}/book-service:latest ${{ secrets.DOCKER_USERNAME }}/book-service:${{ github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/book-service:latest ${{ secrets.DOCKER_USERNAME }}/book-service:latest
          
          docker push ${{ secrets.DOCKER_USERNAME }}/service-registry:${{ github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/gateway:${{ github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME}}/cambio-service:${{ github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/book-service:${{ github.run_id}}
          
        
        
      
   

      


     
